Repository KE-works/pykechain, pull requests merged in 2018-05, with the labels that each got.

#318 support for property validators
  pykechain/__about__.py
  pykechain/enums.py
  pykechain/models/activity.py
  pykechain/models/property.py
  pykechain/models/validators/__init__.py
  pykechain/models/validators/effects.py
  pykechain/models/validators/validator_schemas.py
  pykechain/models/validators/validators.py
  pykechain/models/validators/validators_base.py
  requirements.txt
  tests/cassettes/TestPropertyWithValidatorFromLiveServer.test_numeric_property_add_requiredvalidator_on_instance.json
  tests/cassettes/TestPropertyWithValidatorFromLiveServer.test_numeric_property_add_requiredvalidator_on_model.json
  tests/cassettes/TestPropertyWithValidatorFromLiveServer.test_numeric_property_with_validator_parses.json
  tests/classes.py
  tests/models/test_validators.py
Labels: feature

#321 #320 populate descendants on part models
  pykechain/models/part.py
  tests/cassettes/TestPartRetrieve.test_get_parts_with_descendants_tree.json
  tests/test_parts_retrieve.py
Labels: bug

#327 326 correct property_type used when not specified on property creation
  CHANGELOG.rst
  pykechain/client.py
  pykechain/enums.py
  tests/cassettes/TestProperties.test_creation_of_all_property_model_types.json
  tests/test_properties.py
Labels: bug, testing
