Repository KE-works/pykechain, pull requests merged in 2019-11, with the labels that each got.

#578 Pim3 branch
  CHANGELOG.rst
  pykechain/__about__.py
  pykechain/client.py
  pykechain/enums.py
  pykechain/models/__init__.py
  pykechain/models/activity2.py
  pykechain/models/base.py
  pykechain/models/part2.py
  pykechain/models/property2.py
  pykechain/utils.py
  tests/cassettes/TestParts.test_base_comparison.json
  tests/cassettes/TestParts.test_base_hash.json
  tests/test_enums.py
  tests/test_parts.py
  tests/test_users.py
Labels: enhancement

#579 Move activity implemented
  CHANGELOG.rst
  pykechain/__about__.py
  pykechain/client.py
  pykechain/defaults.py
  pykechain/models/activity2.py
  tests/cassettes/TestActivity2SpecificTests.test_activity2_move.json
  tests/cassettes/TestActivity2SpecificTests.test_activity2_move_under_part_object.json
  tests/cassettes/TestActivity2SpecificTests.test_activity2_move_under_task_parent.json
  tests/test_activities.py
Labels: feature

#591 Parsing the update-dict to remove values that cant be serialized.
  CHANGELOG.rst
  pykechain/__about__.py
  pykechain/models/part2.py
  pykechain/models/property2_datetime.py
  pykechain/utils.py
  requirements.txt
  tests/cassettes/TestPartUpdate.test_part_update_with_attachment.json
  tests/test_parts_update.py
Labels: help wanted

#611 608 - retrieve pykechain objects with 'ref'
  .github/workflows/python_testing.yml
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  tests/cassettes/TestActivity2SpecificTests.test_activity2_retrieve_with_refs.json
  tests/cassettes/TestPartRetrieve.test_retrieve_parts_with_refs.json
  tests/cassettes/TestProperties.test_retrieve_properties_with_refs.json
  tests/cassettes/TestScopes2SpecificTests.test_retrieve_scope_with_refs.json
  tests/cassettes/TestServiceExecutions.test_debug_service_execution_terminate.json
  tests/cassettes/TestServiceExecutions.test_log_of_service_execution.json
  tests/cassettes/TestServiceExecutions.test_properties_of_service_execution.json
  tests/cassettes/TestServiceExecutions.test_retrieve_service_executions.json
  tests/cassettes/TestServiceExecutions.test_retrieve_service_executions_with_kwargs.json
  tests/cassettes/TestServiceExecutions.test_retrieve_single_service_execution.json
  tests/cassettes/TestServiceExecutions.test_retrieve_single_service_execution_but_found_multiple.json
  tests/cassettes/TestServiceExecutions.test_retrieve_single_service_execution_but_found_none.json
  tests/cassettes/TestServiceExecutions.test_service_execution_conflict.json
  tests/cassettes/TestServices.test_debug_service_execute.json
  tests/cassettes/TestServices.test_properties_of_service.json
  tests/cassettes/TestServices.test_retrieve_service_but_found_multiple.json
  tests/cassettes/TestServices.test_retrieve_service_by_name.json
  tests/cassettes/TestServices.test_retrieve_services.json
  tests/cassettes/TestServices.test_retrieve_services_with_kwargs.json
  tests/cassettes/TestServices.test_retrieve_services_with_refs.json
  tests/cassettes/TestServices.test_retrieve_single_service.json
  tests/cassettes/TestServices.test_update_service.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_create_and_delete_service.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_create_service_with_wrong_environment_version.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_create_service_with_wrong_service_type.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_get_executions_of_service.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_save_service_script.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_service_refresh_from_kechain.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_update_service_incorrect_description.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_update_service_incorrect_name.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_update_service_incorrect_version.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_upload_script_to_service.json
  tests/cassettes/TestServicesWithCustomUploadedService.test_upload_script_to_service_with_wrong_path.json
  tests/cassettes/TestWidgetManagerInActivity.test_notebook_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_service_widget.json
  tests/test_activities.py
  tests/test_parts_retrieve.py
  tests/test_properties.py
  tests/test_scope.py
  tests/test_services.py
Labels: enhancement, pim3
