Repository KE-works/pykechain, pull requests merged in 2020-08, with the labels that each got.

#821 #814: Added `upload` input value
  CHANGELOG.rst
  pykechain/models/widgets/widgets_manager.py
Labels: feature, ready for review and merge

#822 812 bulk deletion parts
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  tests/cassettes/TestBulkPartsDeletion.test_bulk_delete_parts.json
  tests/cassettes/TestBulkPartsDeletion.test_bulk_delete_parts_with_wrong_input.json
  tests/test_parts.py
  tox.ini
Labels: enhancement, feature, ready for review and merge

#805 Clone Activity API renaming
  CHANGELOG.rst
  pykechain/__about__.py
  pykechain/client.py
  pykechain/models/activity.py
  pykechain/models/input_checks.py
  tests/cassettes/TestActivityCloneParts.test.json
  tests/cassettes/TestActivityCloneParts.test_excluded_models.json
  tests/test_activities.py
Labels: bug

#828 #827 widget and association methods
  CHANGELOG.rst
  pykechain/client.py
  pykechain/models/widgets/widget.py
  tests/cassettes/TestWidgetManagerInActivity.test_parent.json
  tests/cassettes/TestWidgets.test_associated_parts.json
  tests/test_associations.py
  tests/test_widgets.py
Labels: enhancement, feature

#835 Add ScopeReferenceProperty and UserReferenceProperty
  CHANGELOG.rst
  pykechain/models/__init__.py
  pykechain/models/property2_activity_reference.py
  pykechain/models/property_reference.py
  tests/cassettes/TestScopeReference.test_create.json
  tests/cassettes/TestScopeReference.test_no_value.json
  tests/cassettes/TestScopeReference.test_reload.json
  tests/cassettes/TestScopeReference.test_value.json
  tests/cassettes/TestUserReference.test_create.json
  tests/cassettes/TestUserReference.test_no_value.json
  tests/cassettes/TestUserReference.test_reload.json
  tests/cassettes/TestUserReference.test_value.json
  tests/models/test_property_reference.py
Labels: feature, ready for review and merge
