Repository KE-works/pykechain, pull requests merged in 2020-11, with the labels that each got.

#870 Implemented `BaseFilter` and `ScopeFilter` classes. Added `set_prefil…
  CHANGELOG.rst
  pykechain/models/base_reference.py
  pykechain/models/property_reference.py
  pykechain/models/value_filter.py
  tests/cassettes/TestScopeReference.test_prefilters.json
  tests/cassettes/TestScopeReference.test_value.json
  tests/models/test_property_reference.py
  tests/test_value_filter.py
Labels: enhancement

#875 #873: add Dashboard widget
  CHANGELOG.rst
  pykechain/enums.py
  pykechain/models/widgets/__init__.py
  pykechain/models/widgets/enums.py
  pykechain/models/widgets/widget_models.py
  pykechain/models/widgets/widgets_manager.py
  tests/cassettes/TestWidgetManagerInActivity.test_add_dashboard_widget.json
  tests/test_widgets.py
Labels: feature

#876 Edit meta and title of a widget at the same time
  CHANGELOG.rst
  pykechain/models/widgets/widget.py
  tests/cassettes/TestWidgetManagerInActivity.test_edit_widget_title_and_meta.json
  tests/test_widgets.py
Labels: bug

#877 Implemented `chunks` to retrieve references in batch
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  pykechain/models/base_reference.py
  pykechain/models/part.py
  pykechain/models/property_multi_reference.py
  pykechain/models/property_reference.py
  tests/cassettes/TestPartRetrieve.test_all_children.json
  tests/cassettes/TestPartRetrieve.test_get_models_with_descendants_tree.json
  tests/cassettes/TestPartRetrieve.test_get_parts_with_descendants_tree.json
  tests/cassettes/TestPartsCopyMove.test_copy_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_empty_name_not_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_given_name_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_include_instances.json
  tests/cassettes/TestPartsCopyMove.test_move_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_move_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_move_part_model.json
  tests/models/test_property_reference.py
Labels: agreed, bug

#878 Deprecated customizations
  CHANGELOG.rst
  pykechain/enums.py
  pykechain/models/customization.py
Labels: agreed, decision needed

#881 Minor bugfixes
  CHANGELOG.rst
  pykechain/client.py
  pykechain/models/scope.py
  pykechain/models/widgets/widget.py
  tests/cassettes/TestActivities.test_activity_move.json
  tests/cassettes/TestActivities.test_activity_retrieve_children_of_parent.json
  tests/cassettes/TestActivities.test_activity_retrieve_children_of_subprocess_with_arguments.json
  tests/cassettes/TestActivities.test_activity_retrieve_parent_of_a_toplevel_task_returns_workflow_root_id.json
  tests/cassettes/TestActivities.test_activity_retrieve_parent_of_task.json
  tests/cassettes/TestActivities.test_child.json
  tests/cassettes/TestActivities.test_child_invalid.json
  tests/cassettes/TestActivities.test_edit_cascade_down.json
  tests/cassettes/TestActivities.test_retrieve_all_children.json
  tests/cassettes/TestActivities.test_retrieve_siblings_of_a_task_in_a_subprocess.json
  tests/cassettes/TestActivities.test_retrieve_siblings_of_a_task_in_a_subprocess_with_arguments.json
  tests/cassettes/TestActivityConstruction.test_create_below_parent.json
  tests/cassettes/TestActivityReference.test_value.json
  tests/cassettes/TestActivityReference.test_value_ids.json
  tests/cassettes/TestWidgetManagerInActivity.test_edit_widget_title_is_none.json
  tests/test_parts.py
  tests/test_widgets.py
Labels: bug

#882 Separated name from ref when retrieving a single property
  CHANGELOG.rst
  pykechain/models/part.py
  tests/test_properties.py
Labels: bug

#884 853 refactor meta strings to enums
  CHANGELOG.rst
  pykechain/models/property_multi_reference.py
  pykechain/models/property_reference.py
  pykechain/models/widgets/enums.py
  pykechain/models/widgets/helpers.py
  pykechain/models/widgets/widget.py
  pykechain/models/widgets/widgets_manager.py
Labels: enhancement

#888 Banner bugfix
  CHANGELOG.rst
  pykechain/models/banner.py
Labels: bug

#886 Checks and tests for bulk widget updates
  CHANGELOG.rst
  pykechain/client.py
  pykechain/models/widgets/helpers.py
  pykechain/models/widgets/widget.py
  pykechain/models/widgets/widgets_manager.py
  tests/cassettes/TestWidgets.test_bulk_update.json
  tests/test_widgets.py
Labels: enhancement

#889 Fixes to internal reference _value
  CHANGELOG.rst
  pykechain/models/base_reference.py
  pykechain/models/property_multi_reference.py
  pykechain/models/property_reference.py
  tests/models/test_property_reference.py
  tests/test_utils.py
Labels: bug

#887 set_prefilters validation via provided model
  CHANGELOG.rst
  pykechain/models/property_multi_reference.py
  pykechain/models/widgets/helpers.py
  tests/cassettes/TestMultiReferenceProperty.test_set_prefilters_with_validation.json
  tests/models/test_property_reference.py
Labels: enhancement

#890 Bug updating _value via part.update
  pykechain/models/base_reference.py
  pykechain/models/part.py
  pykechain/models/property_reference.py
  tests/cassettes/TestDateTime.test_value_via_part.json
  tests/cassettes/TestPartUpdate.test_bulk_update.json
  tests/cassettes/TestPartUpdate.test_model.json
  tests/cassettes/TestPartUpdate.test_with_attachment.json
  tests/cassettes/TestPartUpdate.test_with_property_ids.json
  tests/test_parts_update.py
Labels: bug

#891 Lean child() method on Activity
  CHANGELOG.rst
  pykechain/models/activity.py
  pykechain/models/part.py
  pykechain/models/property.py
  tests/cassettes/TestDateTime.test_value_via_part.json
  tests/cassettes/TestPartUpdate.test_bulk_update.json
  tests/cassettes/TestPartUpdate.test_model.json
  tests/cassettes/TestPartUpdate.test_with_attachment.json
  tests/cassettes/TestPartUpdate.test_with_property_ids.json
  tests/test_properties.py
Labels: enhancement

#893 Implemented conditional validation in `set_excluded_propmodels()`
  CHANGELOG.rst
  pykechain/models/property_multi_reference.py
  pykechain/models/widgets/helpers.py
  tests/cassettes/TestMultiReferenceProperty.test_set_excluded_propmodels_with_validation.json
  tests/models/test_property_reference.py
Labels: enhancement
