Repository KE-works/pykechain, pull requests merged in 2020-12, with the labels that each got.

#896 empty value in activity edit
  CHANGELOG.rst
  pykechain/models/activity.py
  tests/test_activities.py
Labels: bug

#899 Add `kwargs` to the edit methods of several classes
  CHANGELOG.rst
  pykechain/models/banner.py
  pykechain/models/scope.py
  pykechain/models/team.py
  tests/cassettes/TestScopeEdit.test_edit_scope.json
  tests/test_scope.py
Labels: enhancement

#902 901 - fixed a small bug on the enums of a widget
  CHANGELOG.rst
  pykechain/models/widgets/widgets_manager.py
Labels: bug

#906 Activity export with QR-code
  CHANGELOG.rst
  pykechain/enums.py
  pykechain/models/activity.py
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_download_as_pdf.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_download_as_pdf_async.json
  tests/test_activities.py
Labels: enhancement

#904 Activity _validate_edit_arguments bugfix
  CHANGELOG.rst
  pykechain/models/activity.py
Labels: bug

#908 count_children methods
  CHANGELOG.rst
  pykechain/models/activity.py
  pykechain/models/part.py
  pykechain/models/tree_traversal.py
  tests/cassettes/TestActivities.test_count_children.json
  tests/cassettes/TestParts.test_count_children.json
  tests/test_activities.py
  tests/test_parts.py
Labels: feature

#909 Implement `download_as_excel` for grid widgets
  CHANGELOG.rst
  pykechain/models/widgets/widget.py
  tests/cassettes/TestWidgetDownloadAsExcel.test_download_as_excel.json
  tests/cassettes/TestWidgetDownloadAsExcel.test_invalid_inputs.json
  tests/cassettes/TestWidgetDownloadAsExcel.test_timezone_aware.json
  tests/test_widgets.py
Labels: feature

#911 kwargs for service executions
  CHANGELOG.rst
  pykechain/models/service.py
  tests/cassettes/TestServices.test_service_context.json
  tests/test_services.py
Labels: enhancement

#913 #912: Fixed a bug regarding the `share_pdf` and `share_link` functionalities
  CHANGELOG.rst
  pykechain/models/activity.py
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_download_as_pdf.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_download_as_pdf_async.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_link.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_pdf.json
Labels: bug

#914 kwargs in count_children
  CHANGELOG.rst
  pykechain/models/activity.py
  pykechain/models/part.py
  tests/cassettes/TestActivities.test_count_children.json
  tests/cassettes/TestParts.test_count_children.json
  tests/test_activities.py
  tests/test_parts.py
Labels: bug
