Repository KE-works/pykechain, pull requests merged in 2020-03, with the labels that each got.

#723 #722: updating `_cached_children` when child Activity2 is created.
  CHANGELOG.rst
  pykechain/client.py
  tests/cassettes/TestActivityConstruction.test_create_below_parent.json
  tests/test_activities.py
Labels: bug

#727 #725: Implemented `Banner` model, client methods and tests.
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  pykechain/models/banner.py
  pykechain/models/property2_multi_reference.py
  tests/cassettes/TestBanners.test_create.json
  tests/cassettes/TestBanners.test_create_empty.json
  tests/cassettes/TestBanners.test_delete.json
  tests/cassettes/TestBanners.test_edit.json
  tests/cassettes/TestBanners.test_get_active_banner.json
  tests/cassettes/TestBanners.test_get_banner.json
  tests/cassettes/TestBanners.test_get_banners.json
  tests/test_banners.py
Labels: feature

#724 #674 - Added notification model
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  pykechain/enums.py
  pykechain/models/activity2.py
  pykechain/models/notification.py
  pykechain/models/service.py
  pykechain/utils.py
  tests/cassettes/TestActivityDownloadAsPDF.test_activity2_download_as_pdf.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity2_download_as_pdf_async.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity2_share_link.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity2_share_pdf.json
  tests/cassettes/TestNotifications.test_all_notifications_retrieval.json
  tests/cassettes/TestNotifications.test_create_notification.json
  tests/cassettes/TestNotifications.test_delete_notification.json
  tests/cassettes/TestNotifications.test_delete_notification_from_client.json
  tests/cassettes/TestNotifications.test_get_recipient_users.json
  tests/cassettes/TestNotifications.test_retrieve_notification.json
  tests/cassettes/TestNotifications.test_retrieve_notification_raise_multiple_found.json
  tests/cassettes/TestNotifications.test_retrieve_notification_raise_not_found.json
  tests/test_activities.py
  tests/test_notifications.py
Labels: feature, pim3, testing
