Repository KE-works/pykechain, pull requests merged in 2020-07, with the labels that each got.

#801 #654 Fixed bulk operations on side-bar manager and increased coverage
  CHANGELOG.rst
  pykechain/enums.py
  pykechain/models/sidebar/sidebar_button.py
  pykechain/models/sidebar/sidebar_manager.py
  tests/cassettes/TestSideBar.test_add_buttons.json
  tests/cassettes/TestSideBar.test_bulk_add_buttons.json
  tests/cassettes/TestSideBar.test_bulk_creation.json
  tests/cassettes/TestSideBar.test_context_manager.json
  tests/cassettes/TestSideBar.test_create_button.json
  tests/cassettes/TestSideBar.test_create_button_incorrect_arguments.json
  tests/cassettes/TestSideBar.test_delete_button.json
  tests/cassettes/TestSideBar.test_edit_button.json
  tests/cassettes/TestSideBar.test_get_button.json
  tests/cassettes/TestSideBar.test_insert_button.json
  tests/cassettes/TestSideBar.test_loading_of_existing_buttons.json
  tests/cassettes/TestSideBar.test_manager.json
  tests/cassettes/TestSideBar.test_override_sidebar_property.json
  tests/cassettes/TestSideBar.test_remove_button.json
  tests/cassettes/TestSideBar.test_singleton_manager_per_scope.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_card_widget_ke_chain_pages.json
  tests/test_sidebar.py
  tests/test_widgets.py
Labels: bug, enhancement

#806 Bugfixes SideBarManager (#806)
  pykechain/models/sidebar/sidebar_button.py
  pykechain/models/sidebar/sidebar_manager.py
  tests/cassettes/TestSideBar.test_bulk_add_buttons.json
  tests/cassettes/TestSideBar.test_context_manager.json
  tests/test_sidebar.py
Labels: bug

#807 Sidebar config typo (#807)
  pykechain/models/sidebar/sidebar_manager.py
  tests/cassettes/TestSideBar.test_context_manager.json
  tests/cassettes/TestSideBar.test_load_buttons.json
  tests/test_sidebar.py
Labels: bug

#811 797 bulk part creation
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  tests/cassettes/TestBulkPartsCreation.test_bulk_create_parts.json
  tests/cassettes/TestBulkPartsCreation.test_bulk_create_parts_without_model_id.json
  tests/cassettes/TestBulkPartsCreation.test_bulk_create_parts_without_name.json
  tests/cassettes/TestBulkPartsCreation.test_bulk_create_parts_without_parent_id.json
  tests/cassettes/TestBulkPartsCreation.test_bulk_create_parts_without_properties.json
  tests/cassettes/TestBulkPartsCreation.test_bulk_create_parts_without_property_model_id.json
  tests/cassettes/TestBulkPartsCreation.test_bulk_create_parts_without_property_name.json
  tests/cassettes/TestBulkPartsCreation.test_bulk_create_parts_without_property_value.json
  tests/test_parts.py
Labels: enhancement, feature
