Repository KE-works/pykechain, pull requests merged in 2020-10, with the labels that each got.

#852 844 service card widget
  CHANGELOG.rst
  pykechain/enums.py
  pykechain/models/widgets/__init__.py
  pykechain/models/widgets/helpers.py
  pykechain/models/widgets/widget_models.py
  pykechain/models/widgets/widgets_manager.py
  tests/cassettes/TestWidgetManagerInActivity.test_add_attachment_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_attachment_widget_with_associations_using_widget_manager.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_attachment_widget_with_editable_association.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_card_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_card_widget_ke_chain_pages.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_filtered_grid_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_filtered_grid_widget_with_prefilters_and_excluded_propmodels.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_html_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_metapanel_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_metapanel_with_progress_settings.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_multicolumn_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_notebook_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_progress_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_propertygrid_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_scope_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_service_card_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_service_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_signature_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_add_super_grid_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_attachment_widget_with_associations_using_widget_manager.json
  tests/cassettes/TestWidgetManagerInActivity.test_attachment_widget_with_editable_association.json
  tests/cassettes/TestWidgetManagerInActivity.test_create_widgets.json
  tests/cassettes/TestWidgetManagerInActivity.test_delete_all_widgets.json
  tests/cassettes/TestWidgetManagerInActivity.test_delete_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_delete_widget_stand_alone.json
  tests/cassettes/TestWidgetManagerInActivity.test_edit_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_edit_widget_meta.json
  tests/cassettes/TestWidgetManagerInActivity.test_edit_widget_title.json
  tests/cassettes/TestWidgetManagerInActivity.test_insert_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_metapanel_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_multicolumn_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_new_widget_using_widget_manager.json
  tests/cassettes/TestWidgetManagerInActivity.test_notebook_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_parent.json
  tests/cassettes/TestWidgetManagerInActivity.test_progress_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_property_grid_with_associations_using_widget_manager.json
  tests/cassettes/TestWidgetManagerInActivity.test_scope_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_scope_widget_invalid_inputs.json
  tests/cassettes/TestWidgetManagerInActivity.test_service_widget.json
  tests/cassettes/TestWidgetManagerInActivity.test_widget_title.json
  tests/test_widgets.py
Labels: feature, ready for review and merge

#841 Wabco features
  CHANGELOG.rst
  pykechain/client.py
  pykechain/enums.py
  pykechain/models/__init__.py
  pykechain/models/part.py
  pykechain/models/property.py
  pykechain/models/property_multi_reference.py
  pykechain/models/value_filter.py
  pykechain/models/widgets/helpers.py
  pykechain/models/widgets/widgets_manager.py
  tests/cassettes/TestMultiReferenceProperty.test_add_prefilters_to_reference_property.json
  tests/cassettes/TestMultiReferenceProperty.test_clear_prefilters.json
  tests/cassettes/TestMultiReferenceProperty.test_get_excluded_propmodel_ids.json
  tests/cassettes/TestMultiReferenceProperty.test_get_prefilters.json
  tests/cassettes/TestMultiReferenceProperty.test_overwrite_prefilters.json
  tests/cassettes/TestMultiReferenceProperty.test_set_prefilters_on_reference_property.json
  tests/cassettes/TestMultiReferenceProperty.test_set_prefilters_with_tuples.json
  tests/cassettes/TestPropertyValueFilter.test__eq__.json
  tests/cassettes/TestPropertyValueFilter.test_creation.json
  tests/cassettes/TestPropertyValueFilter.test_format.json
  tests/cassettes/TestPropertyValueFilter.test_parse_options.json
  tests/cassettes/TestPropertyValueFilter.test_repr.json
  tests/cassettes/TestPropertyValueFilter.test_validate.json
  tests/models/test_property_reference.py
  tests/test_value_filter.py
Labels: enhancement, feature

#773 added add/remove supervisor member management methods on `Scope`
  .pre-commit-config.yaml
  CHANGELOG.rst
  pykechain/defaults.py
  pykechain/enums.py
  pykechain/models/scope.py
  tests/cassettes/TestScopeMembers.test_add_leadmember.json
  tests/cassettes/TestScopeMembers.test_add_manager.json
  tests/cassettes/TestScopeMembers.test_add_member.json
  tests/cassettes/TestScopeMembers.test_add_member_by_id.json
  tests/cassettes/TestScopeMembers.test_add_non_existing_member.json
  tests/cassettes/TestScopeMembers.test_add_supervisor.json
  tests/cassettes/TestScopeMembers.test_members.json
  tests/cassettes/TestScopeMembers.test_remove_leadmember.json
  tests/cassettes/TestScopeMembers.test_remove_manager.json
  tests/cassettes/TestScopeMembers.test_remove_member.json
  tests/cassettes/TestScopeMembers.test_remove_supervisor.json
  tests/cassettes/TestScopeMembers.test_reset_members.json
  tests/test_scope.py
Labels: feature, on hold, ready for review and merge

#868 Implemented `ref` keyword for activities
  CHANGELOG.rst
  pykechain/client.py
  tests/cassettes/TestActivityConstruction.test_create_with_inputs.json
  tests/test_activities.py
Labels: enhancement
