Repository KE-works/pykechain, pull requests merged in 2020-02, with the labels that each got.

#670 669 thousand separators
  pykechain/enums.py
  pykechain/models/representations/representations.py
  tests/cassettes/TestButtonRepresentationLive.test_getter.json
  tests/cassettes/TestButtonRepresentationLive.test_set_value.json
  tests/cassettes/TestButtonRepresentationLive.test_setter.json
  tests/cassettes/TestButtonRepresentationLive.test_unsupported_value.json
  tests/cassettes/TestDecimalPlacesLive.test_getter.json
  tests/cassettes/TestDecimalPlacesLive.test_set_value.json
  tests/cassettes/TestDecimalPlacesLive.test_setter.json
  tests/cassettes/TestDecimalPlacesLive.test_unsupported_value.json
  tests/cassettes/TestLinkTargetLive.test_getter.json
  tests/cassettes/TestLinkTargetLive.test_set_value.json
  tests/cassettes/TestLinkTargetLive.test_setter.json
  tests/cassettes/TestLinkTargetLive.test_unsupported_value.json
  tests/cassettes/TestSignificantDigitsLive.test_getter.json
  tests/cassettes/TestSignificantDigitsLive.test_set_value.json
  tests/cassettes/TestSignificantDigitsLive.test_setter.json
  tests/cassettes/TestSignificantDigitsLive.test_unsupported_value.json
  tests/cassettes/TestThousandsSeparatorLive.test_getter.json
  tests/cassettes/TestThousandsSeparatorLive.test_set_value.json
  tests/cassettes/TestThousandsSeparatorLive.test_setter.json
  tests/cassettes/TestThousandsSeparatorLive.test_unsupported_value.json
  tests/models/test_representations.py
Labels: feature

#678 468 - added tests on Part Reference Properties
  .github/workflows/python_testing.yml
  .github/workflows/release_notifier.yml-OFF
  CHANGELOG.rst
  pykechain/models/widgets/widget.py
  tests/cassettes/TestMultiReferenceProperty.test_add_excluded_propmodels_to_reference_property.json
  tests/cassettes/TestMultiReferenceProperty.test_add_prefilters_to_reference_property.json
  tests/cassettes/TestMultiReferenceProperty.test_create_ref_property_referencing_id.json
  tests/cassettes/TestMultiReferenceProperty.test_create_ref_property_referencing_id_in_list.json
  tests/cassettes/TestMultiReferenceProperty.test_create_ref_property_referencing_part.json
  tests/cassettes/TestMultiReferenceProperty.test_create_ref_property_referencing_part_in_list.json
  tests/cassettes/TestMultiReferenceProperty.test_create_ref_property_wrongly_referencing.json
  tests/cassettes/TestMultiReferenceProperty.test_create_ref_property_wrongly_referencing_in_list.json
  tests/cassettes/TestMultiReferenceProperty.test_multi_ref_choices.json
  tests/cassettes/TestMultiReferenceProperty.test_overwrite_excluded_propmodels_on_reference_property.json
  tests/cassettes/TestMultiReferenceProperty.test_overwrite_prefilters_on_reference_property.json
  tests/cassettes/TestMultiReferenceProperty.test_property_clear_referenced_part_instances.json
  tests/cassettes/TestMultiReferenceProperty.test_property_clear_selected_part_model.json
  tests/cassettes/TestMultiReferenceProperty.test_referencing_a_list_with_no_parts.json
  tests/cassettes/TestMultiReferenceProperty.test_referencing_a_model.json
  tests/cassettes/TestMultiReferenceProperty.test_referencing_a_part_not_in_a_list.json
  tests/cassettes/TestMultiReferenceProperty.test_referencing_multiple_instances_using_ids.json
  tests/cassettes/TestMultiReferenceProperty.test_referencing_multiple_instances_using_parts.json
  tests/cassettes/TestMultiReferenceProperty.test_retrieve_scope_id.json
  tests/cassettes/TestMultiReferenceProperty.test_set_excluded_propmodels_on_reference_property.json
  tests/cassettes/TestMultiReferenceProperty.test_set_excluded_propmodels_on_reference_property_the_wrong_way.json
  tests/cassettes/TestMultiReferenceProperty.test_set_excluded_propmodels_on_reference_property_using_uuid.json
  tests/cassettes/TestMultiReferenceProperty.test_set_excluded_propmodels_on_reference_property_with_prefilters_and_validators.json
  tests/cassettes/TestMultiReferenceProperty.test_set_prefilters_on_reference_property.json
  tests/cassettes/TestMultiReferenceProperty.test_set_prefilters_on_reference_property_the_wrong_way.json
  tests/cassettes/TestMultiReferenceProperty.test_set_prefilters_on_reference_property_using_uuid.json
  tests/cassettes/TestMultiReferenceProperty.test_set_prefilters_on_reference_property_with_excluded_propmodels_and_validators.json
  tests/cassettes/TestMultiReferenceProperty.test_value_if_multi_ref_gives_back_all_parts.json
  tests/cassettes/TestMultiReferenceProperty.test_value_if_nothing_is_referenced.json
  tests/cassettes/TestMultiReferencePropertyXScope.test_set_model_value.json
  tests/cassettes/TestMultiReferencePropertyXScope.test_set_model_value_using_id.json
  tests/cassettes/TestMultiReferencePropertyXScope.test_set_value.json
  tests/cassettes/TestWidgets.test_create_widget_in_activity.json
  tests/cassettes/TestWidgets.test_create_widgets.json
  tests/cassettes/TestWidgets.test_retrieve_widgets_in_activity.json
  tests/cassettes/TestWidgets.test_widget_attributes.json
  tests/cassettes/TestWidgets.test_widget_meta_attribute_is_not_None.json
  tests/models/test_property_reference.py
Labels: testing

#664 663 bulk update properties
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  pykechain/models/property2.py
  tests/cassettes/TestPropertiesWithReferenceProperty.test_copy_reference_property_with_options.json
  tests/cassettes/TestUpdateProperties.test_bulk_update.json
  tests/cassettes/TestUpdateProperties.test_bulk_update_manual.json
  tests/cassettes/TestUpdateProperties.test_bulk_update_reset.json
  tests/test_properties.py
Labels: feature

#680 658 bulk update widgets
  CHANGELOG.rst
  pykechain/client.py
  pykechain/models/widgets/widgets_manager.py
Labels: enhancement

#698 #697: Child method and TreeObject superclass
  CHANGELOG.rst
  pykechain/helpers.py
  pykechain/models/activity2.py
  pykechain/models/part2.py
  pykechain/models/tree_traversal.py
  tests/cassettes/TestActivities.test_child.json
  tests/cassettes/TestActivities.test_child_invalid.json
  tests/cassettes/TestActivities.test_edit_cascade_down.json
  tests/cassettes/TestActivities.test_retrieve_all_children.json
  tests/cassettes/TestPartRetrieve.test_all_children.json
  tests/cassettes/TestPartRetrieve.test_child.json
  tests/cassettes/TestPartRetrieve.test_child_caching.json
  tests/cassettes/TestPartRetrieve.test_child_invalid.json
  tests/test_activities.py
  tests/test_parts_retrieve.py
Labels: enhancement, feature

#689 688 set and clear associations
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  pykechain/models/__init__.py
  pykechain/models/association.py
  tests/cassettes/TestAssociations.test_association_attributes.json
  tests/cassettes/TestAssociations.test_clear_associations.json
  tests/cassettes/TestAssociations.test_input_lengths.json
  tests/cassettes/TestAssociations.test_readable_models.json
  tests/cassettes/TestAssociations.test_remove_associations.json
  tests/cassettes/TestAssociations.test_retrieve_association_incorrect_inputs.json
  tests/cassettes/TestAssociations.test_retrieve_associations.json
  tests/cassettes/TestAssociations.test_retrieve_associations_interface.json
  tests/cassettes/TestAssociations.test_set_associations.json
  tests/cassettes/TestAssociations.test_set_associations_empty.json
  tests/cassettes/TestAssociations.test_update_associations_empty.json
  tests/cassettes/TestAssociations.test_update_widget_associations.json
  tests/cassettes/TestAssociations.test_validate_model_input.json
  tests/cassettes/TestAssociations.test_validate_widget_input.json
  tests/cassettes/TestAssociations.test_validate_widgets_input.json
  tests/cassettes/TestAssociations.test_widget_inputs.json
  tests/cassettes/TestAssociations.test_writable_models.json
  tests/cassettes/TestWidgetManagerInActivity.test_insert_widget.json
  tests/test_associations.py
  tests/test_widgets.py
Labels: feature

#701 700 bug hunt mark ii
  CHANGELOG.rst
  pykechain/models/activity2.py
  pykechain/models/part2.py
  pykechain/models/property2_multi_reference.py
  pykechain/models/tree_traversal.py
  pykechain/models/widgets/helpers.py
  tests/cassettes/TestMultiReferenceProperty.test_referencing_multiple_instances_using_ids.json
  tests/cassettes/TestMultiReferenceProperty.test_referencing_multiple_instances_using_parts.json
  tests/cassettes/TestMultiReferenceProperty.test_set_excluded_propmodels_on_reference_property_the_wrong_way.json
  tests/cassettes/TestMultiReferenceProperty.test_set_excluded_propmodels_on_reference_property_using_uuid.json
  tests/cassettes/TestMultiReferenceProperty.test_value_if_multi_ref_gives_back_all_parts.json
  tests/cassettes/TestMultiReferencePropertyXScope.test_set_value.json
  tests/test_parts.py
Labels: enhancement

#704 Various fixes
  CHANGELOG.rst
  pykechain/models/__init__.py
  pykechain/models/activity2.py
  pykechain/models/part2.py
  pykechain/models/tree_traversal.py
  pykechain/models/widgets/helpers.py
  pykechain/models/widgets/widgets_manager.py
  tests/cassettes/TestWidgetManagerInActivity.test_add_html_widget.json
  tests/test_widgets.py
Labels: bug, enhancement

#708 #707: bug-fix relating to parallel creation and retrieval of child parts
  CHANGELOG.rst
  pykechain/client.py
  pykechain/models/part2.py
  pykechain/models/property2_multi_reference.py
  tests/cassettes/TestMultiReferenceProperty.test_referencing_multiple_instances_using_ids.json
  tests/cassettes/TestMultiReferenceProperty.test_referencing_multiple_instances_using_parts.json
  tests/cassettes/TestMultiReferenceProperty.test_value_if_multi_ref_gives_back_all_parts.json
  tests/cassettes/TestMultiReferencePropertyXScope.test_set_value.json
  tests/cassettes/TestPartRetrieve.test_child_after_construction.json
  tests/test_parts_retrieve.py
Labels: bug
