Repository KE-works/pykechain, pull requests merged in 2020-06, with the labels that each got.

#768 Enable new property types
  CHANGELOG.rst
  pykechain/__about__.py
  pykechain/enums.py
Labels: bug

#780 Missing front-end features
  CHANGELOG.rst
  pykechain/__about__.py
  pykechain/enums.py
  pykechain/models/representations/__init__.py
  pykechain/models/representations/component.py
  pykechain/models/representations/representation_base.py
  pykechain/models/representations/representations.py
  pykechain/models/widgets/widgets_manager.py
  tests/cassettes/TestReprAutofill.test_get_set.json
  tests/cassettes/TestReprAutofill.test_set_value.json
  tests/cassettes/TestReprAutofill.test_unsupported_value.json
  tests/cassettes/TestWidgetManagerInActivity.test_metapanel_widget.json
  tests/models/test_representations.py
Labels: bug, feature

#782 #781 refresh activities from reference property
  CHANGELOG.rst
  pykechain/models/property2_activity_reference.py
  tests/cassettes/TestActivityReference.test_value.json
Labels: bug

#792 Added property GeoJSON and Weather Properties
  CHANGELOG.rst
  pykechain/enums.py
Labels: enhancement

#795 #788 adding weather widget and tests (all pass)
  CHANGELOG.rst
  pykechain/enums.py
  pykechain/models/widgets/widget_models.py
  pykechain/models/widgets/widgets_manager.py
  tests/cassettes/TestWidgetManagerWeatherWidget.test_weather_widget.json
  tests/test_widgets.py
Labels: feature
