Repository KE-works/pykechain, pull requests merged in 2021-06, with the labels that each got.

#990 984 user reference property copy bug
  CHANGELOG.rst
  pykechain/extra_utils.py
  tests/cassettes/TestActivityClone.test_update_incorrect.json
  tests/cassettes/TestNotificationCreation.test_create_invalid_inputs.json
  tests/cassettes/TestNotifications.test_edit_incorrect_inputs.json
  tests/cassettes/TestParts.test_clone_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_attachments.json
  tests/cassettes/TestPartsCopyMove.test_copy_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_copy_internal_references_on_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_internal_references_on_model.json
  tests/cassettes/TestPartsCopyMove.test_copy_missing_target_parent_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_empty_name_not_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_given_name_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_include_instances.json
  tests/cassettes/TestPartsCopyMove.test_copy_target_parent_inside_tree.json
  tests/cassettes/TestPartsCopyMove.test_copy_too_many_target_parent_instances.json
  tests/cassettes/TestPartsCopyMove.test_move_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_move_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_move_part_model.json
  tests/test_parts_copy_move.py
Labels: agreed, bug

#994 993 filter bug
  CHANGELOG.rst
  pykechain/enums.py
  pykechain/models/value_filter.py
  tests/cassettes/TestFilterAllPropertyTypes.test_activity_reference_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_activity_reference_property_prefilter.json
  tests/cassettes/TestFilterAllPropertyTypes.test_boolean_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_date_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_float_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_int_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_link_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_multi_select_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_multi_test_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_part_reference_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_part_reference_property_prefilter.json
  tests/cassettes/TestFilterAllPropertyTypes.test_scope_reference_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_single_select_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_text_property_filter_in_grid.json
  tests/cassettes/TestFilterAllPropertyTypes.test_user_reference_property_filter_in_grid.json
  tests/cassettes/TestPartsCopyMove.test_copy_attachments.json
  tests/cassettes/TestPartsCopyMove.test_copy_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_copy_internal_references_on_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_internal_references_on_model.json
  tests/cassettes/TestPartsCopyMove.test_copy_missing_target_parent_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_empty_name_not_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_given_name_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_include_instances.json
  tests/cassettes/TestPartsCopyMove.test_copy_target_parent_inside_tree.json
  tests/cassettes/TestPartsCopyMove.test_copy_too_many_target_parent_instances.json
  tests/cassettes/TestPartsCopyMove.test_move_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_move_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_move_part_model.json
  tests/cassettes/TestPropertyValueFilter.test__eq__.json
  tests/cassettes/TestPropertyValueFilter.test_creation.json
  tests/cassettes/TestPropertyValueFilter.test_format.json
  tests/cassettes/TestPropertyValueFilter.test_parse_options.json
  tests/cassettes/TestPropertyValueFilter.test_repr.json
  tests/cassettes/TestPropertyValueFilter.test_validate.json
  tests/cassettes/TestPropertyValueFilter.test_write_options.json
  tests/test_value_filter.py
Labels: bug

#998 996 - fixed the cassettes on date check
  CHANGELOG.rst
  tests/cassettes/TestPartsCopyMove.test_copy_attachments.json
  tests/cassettes/TestPartsCopyMove.test_copy_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_copy_internal_references_on_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_internal_references_on_model.json
  tests/cassettes/TestPartsCopyMove.test_copy_missing_target_parent_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_empty_name_not_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_given_name_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_include_instances.json
  tests/cassettes/TestPartsCopyMove.test_copy_target_parent_inside_tree.json
  tests/cassettes/TestPartsCopyMove.test_copy_too_many_target_parent_instances.json
  tests/cassettes/TestPartsCopyMove.test_move_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_move_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_move_part_model.json
  tests/test_parts_copy_move.py
Labels: bug, testing

#1001 Refactor the Scope2, Part2 and other '2' models
  CHANGELOG.rst
  pykechain/exceptions.py
  pykechain/models/activity.py
  pykechain/models/activity2.py
  pykechain/models/part.py
  pykechain/models/part2.py
  pykechain/models/property.py
  pykechain/models/property2.py
  pykechain/models/property2_activity_reference.py
  pykechain/models/property2_attachment.py
  pykechain/models/property2_datetime.py
  pykechain/models/property2_multi_reference.py
  pykechain/models/property2_selectlist.py
  pykechain/models/property_attachment.py
  pykechain/models/property_datetime.py
  pykechain/models/property_multi_reference.py
  pykechain/models/property_reference.py
  pykechain/models/property_selectlist.py
  pykechain/models/scope.py
  pykechain/models/scope2.py
Labels: enhancement, ready for review and merge

#1002 Deprecation of python 3.5 due to lack of f-strings
  .github/workflows/python_testing.yml
  CHANGELOG.rst
  setup.py
  tests/test_about.py
  tox.ini
Labels: enhancement, ready for review and merge

#1004 999 enable kwargs on share activity
  pykechain/models/activity.py
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_download_as_pdf.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_download_as_pdf_async.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_link.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_link_with_from_user.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_pdf.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_pdf_with_from_user.json
  tests/test_activities.py
Labels: enhancement

#995 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: ready for review and merge

#1005 KE-1052 Implement custom Retry class
  CHANGELOG.rst
  pykechain/client.py
  pykechain/client_utils.py
  tests/test_retry.py
Labels: enhancement

#982 KE-925 started with scaffold for a Context Model
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  pykechain/enums.py
  pykechain/models/activity.py
  pykechain/models/banner.py
  pykechain/models/context.py
  pykechain/models/input_checks.py
  pykechain/models/part.py
  pykechain/models/property.py
  pykechain/models/property2_selectlist.py
  pykechain/models/scope.py
  pykechain/models/scope2.py
  pykechain/models/service.py
  pykechain/typing.py
  requirements.txt
  tests/cassettes/TestContextCreate.test_create_context.json
  tests/cassettes/TestContexts.test_context_consequetive_link_many_activities.json
  tests/cassettes/TestContexts.test_context_unlink_single_activity_when_more_activities.json
  tests/cassettes/TestContexts.test_create_contexts_bound_to_an_activity.json
  tests/cassettes/TestContexts.test_link_context_to_activity.json
  tests/cassettes/TestContexts.test_retrieve_contexts_via_client_using_scope_filter.json
  tests/cassettes/TestContexts.test_retrieve_multiple_context_via_client_using_filters.json
  tests/cassettes/TestContexts.test_retrieve_single_context_via_client_with_pk_filter.json
  tests/cassettes/TestContexts.test_unlink_context_to_activity.json
  tests/test_activities.py
  tests/test_banners.py
  tests/test_contexts.py
  tests/test_notifications.py
  tests/test_parts.py
  tests/test_properties.py
  tests/test_scope.py
  tests/test_services.py
Labels: feature, ready for review and merge
