Repository KE-works/pykechain, pull requests merged in 2022-03, with the labels that each got.

#1118 1108 nice to haves
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  pykechain/models/form.py
  tests/cassettes/TestForms.test_form_has_part_is_false.json
  tests/cassettes/TestForms.test_form_has_part_is_true.json
  tests/cassettes/TestForms.test_form_has_part_wrong_inputs.json
  tests/cassettes/TestForms.test_form_workflow_compatible_within_scope.json
  tests/cassettes/TestForms.test_form_workflow_compatible_within_scope_wrong_inputs.json
  tests/cassettes/TestForms.test_model_clone_cross_scope.json
  tests/cassettes/TestForms.test_model_clone_no_target_scope.json
  tests/cassettes/TestForms.test_model_clone_same_scope.json
  tests/test_forms.py
Labels: testing, forms

#1124 1123 extend dashboard widget for forms
  CHANGELOG.rst
  pykechain/models/widgets/enums.py
  pykechain/models/widgets/widgets_manager.py
  tests/cassettes/TestWidgetManagerInActivity.test_add_dashboard_widget.json
  tests/test_widgets.py
Labels: enhancement, testing, forms

#1130 No `offset` parameter is passed to the request of downloading a PDF
  pykechain/models/activity.py
  pykechain/utils.py
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_download_as_pdf.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_download_as_pdf_async.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_link.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_link_with_from_user.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_pdf.json
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_share_pdf_with_from_user.json
  tests/test_activities.py
Labels: bug
