Repository KE-works/pykechain, pull requests merged in 2022-05, with the labels that each got.

#1148 Fix the prefilters when copying a part
  CHANGELOG.rst
  pykechain/models/value_filter.py
  tests/cassettes/TestPartsCopyMove.test_copy_attachments.json
  tests/cassettes/TestPartsCopyMove.test_copy_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_copy_internal_references_on_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_internal_references_on_model.json
  tests/cassettes/TestPartsCopyMove.test_copy_missing_target_parent_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_empty_name_not_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_given_name_include_children.json
  tests/cassettes/TestPartsCopyMove.test_copy_part_model_include_instances.json
  tests/cassettes/TestPartsCopyMove.test_copy_target_parent_inside_tree.json
  tests/cassettes/TestPartsCopyMove.test_copy_too_many_target_parent_instances.json
  tests/cassettes/TestPartsCopyMove.test_cross_scope_copy.json
  tests/cassettes/TestPartsCopyMove.test_move_different_categories.json
  tests/cassettes/TestPartsCopyMove.test_move_part_instance.json
  tests/cassettes/TestPartsCopyMove.test_move_part_model.json
  tests/test_parts_copy_move.py
Labels: bug

#1152 remove order from the sidebaritems.
  CHANGELOG.rst
  pykechain/__about__.py
  pykechain/models/sidebar/sidebar_base.py
  pykechain/models/sidebar/sidebar_button.py
  pykechain/models/sidebar/sidebar_card.py
  pykechain/models/sidebar/sidebar_manager.py
  tests/test_sidebar.py
Labels: enhancement, feature, agreed, ready for review and merge

#1154 KE-2262 add create_workflow to client and scope object
  CHANGELOG.rst
  pykechain/client.py
  pykechain/models/scope.py
  pykechain/models/workflow.py
  tests/cassettes/TestWorkflows.test_create_a_new_workflow_using_classmethod_create_workflow.json
  tests/cassettes/TestWorkflows.test_create_a_new_workflow_using_client_create_workflow.json
  tests/cassettes/TestWorkflows.test_create_a_new_workflow_using_scope_create_workflow.json
  tests/test_workflows.py
Labels: feature, agreed
