Repository KE-works/pykechain, pull requests merged in 2022-04, with the labels that each got.

#1139 1038-passing-kwargs-when-saving-an-attachment
  CHANGELOG.rst
  pykechain/enums.py
  pykechain/models/property_attachment.py
  requirements-ci.txt
  tests/cassettes/TestActivityDownloadAsPDF.test_activity_download_as_pdf.json
  tests/files/test_upload_image_to_attachment_property/test_upload_image.png
  tests/models/test_property_attachment.py
Labels: enhancement

#1140 Status References Property implementation
  CHANGELOG.rst
  pykechain/defaults.py
  pykechain/enums.py
  pykechain/models/__init__.py
  pykechain/models/property_reference.py
  tests/cassettes/TestPropertyStatusReferences.test_create.json
  tests/cassettes/TestPropertyStatusReferences.test_multiple_values.json
  tests/cassettes/TestPropertyStatusReferences.test_no_value_instance.json
  tests/cassettes/TestPropertyStatusReferences.test_no_value_model.json
  tests/cassettes/TestPropertyStatusReferences.test_value_instance.json
  tests/cassettes/TestPropertyStatusReferences.test_value_model.json
  tests/models/test_property_reference.py
Labels: feature, agreed, ready for review and merge

#1142 Create User Endpoint
  CHANGELOG.rst
  pykechain/client.py
  pykechain/defaults.py
  pykechain/models/user.py
  tests/test_users.py
Labels: feature, agreed

#1146 Added configurable timeout on PDF download
  pykechain/defaults.py
  pykechain/exceptions.py
  pykechain/models/activity.py
Labels: enhancement, feature, ready for review and merge

#1144 added Forms classification for Part World in pykechain
  CHANGELOG.rst
  pykechain/enums.py
  tests/cassettes/TestPartsClassificationForm.test_classification_forms_exist.json
  tests/test_parts.py
Labels: feature, agreed
